apiVersion: v1
kind: ConfigMap
metadata:
  name: academy-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.backend.port }}"
  NODE_ENV: "production"
  CLIENT_URL: "https://{{ .Values.domain }}"
