apiVersion: v1
kind: Secret
metadata:
  name: academy-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "{{ .Values.secrets.mongoRootUser }}"
  MONGO_INITDB_ROOT_PASSWORD: "{{ .Values.secrets.mongoRootPassword }}"
  MONGO_URI: "mongodb://{{ .Values.secrets.mongoRootUser }}:{{ .Values.secrets.mongoRootPassword }}@mongo:27017/devops_academy?authSource=admin"
  JWT_SECRET: "{{ .Values.secrets.jwtSecret }}"
  ADMIN_USERNAME: "{{ .Values.secrets.adminUsername }}"
  ADMIN_PASSWORD: "{{ .Values.secrets.adminPassword }}"
  SMTP_HOST: "{{ .Values.secrets.smtpHost }}"
  SMTP_PORT: "{{ .Values.secrets.smtpPort }}"
  SMTP_USER: "{{ .Values.secrets.smtpUser }}"
  SMTP_PASS: "{{ .Values.secrets.smtpPass }}"
