apiVersion: v1
kind: Secret
metadata:
  name: academy-secrets
  namespace: devops-academy
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "replace-with-a-strong-password"
  MONGO_URI: "mongodb://root:replace-with-a-strong-password@mongo:27017/devops_academy?authSource=admin"
  JWT_SECRET: "replace-with-openssl-rand-hex-48-output"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "replace-with-a-real-password"
  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USER: ""
  SMTP_PASS: ""