global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    file_sd_configs:
      - files: ['/etc/prometheus/targets/node-exporter.json']
        refresh_interval: 1m

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['__APP_SERVER_IP__:8081']
